### PR TITLE
initial conversion to run on actions

### PR DESCRIPTION
**Pull request by cpanato**
- initial conversion to run peribolos using GitHub actions
- build the image using `ko`

this is way far to be a nice code, but it is an initial change

I've built the image and push to my personal registry `docker.io/ctadeu/peribolos:latest` and setup some actions to test in a test GitHub org - https://github.com/kingdom-tower/testing
- Was able to add new users, sync teams, create a repository 
- one sample run https://github.com/kingdom-tower/testing/runs/5480354890?check_suite_focus=true
- for now we need to setup a token that have admin permission to run, the GitHub actions permissions seems to not work in this case

Did not the sample Github Actions because I would like to get some feedback and see how we can move forward to start using this asap and improve this fast as well

cc @justaugustus @dlorenc

### CODE REVIEW

**Comment by cpanato** [comment]
but basically i've setup this action

```yaml
name: periobolos-check

on:
  pull_request:

permissions: read-all

jobs:
  check-config:
    name: check-config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v2.4.0
      - name: set token
        run: echo ${{ secrets.PAT_TOKEN }} > token
      - name: Peribolos
        uses: docker://docker.io/ctadeu/peribolos:latest
        with:
          config-path: ./config.yaml
          github-token-path: ./token
          fix-org: true
          fix-org-members: true
          fix-repos: true
          fix-team-repos: true
          fix-teams: true
          fix-teams-members: true
          min-admins: 2

```

**Review by justaugustus — APPROVED** [review]
@cpanato -- I have design thoughts, but lacking the time to properly express them and I don't want to block progress, so let's merge + iterate.

Thanks for taking the first run at this!!

**Comment by cpanato** [comment]
@justaugustus yes, I try to keep the changes to a minimum, because I would like to hear your thoughts, let me know when you have some time then we can discuss the next steps, but I can work on some small improvements.

and maybe we can integrate this in this org to use as dogfood

**Comment by justaugustus** [comment]
> @justaugustus yes, I try to keep the changes to a minimum, because I would like to hear your thoughts, let me know when you have some time then we can discuss the next steps, but I can work on some small improvements.

As a next step, can you work on fixing the tests?
Example failure: https://github.com/relengfam/peribolos/runs/5492510626?check_suite_focus=true

Can you also get us back to feature parity with upstream by re-enabling these flags:

https://github.com/relengfam/peribolos/blob/74808390dad07a5acac6bbab60bcf07a4736da1d/main.go#L200-206

> and maybe we can integrate this in this org to use as dogfood

Absolutely!! We can turn that on once we've built up a bit of confidence with the code.

**Pull request merged**
