### PR TITLE
Allow local runs and simulating GitHub Actions environment

### PR DESCRIPTION
**Pull request by cpanato**
i was not happy to not be able to run locally as well, then I think in a way to be able to run as GitHub action and as a standard command line.

There is a new flag that is always set to `true` that turns to read the parameters from GitHub action, if you set that to false you will need to pass the parameters as normal flags

now both can be used

### CODE REVIEW

**Comment by justaugustus** [comment]
@cpanato -- I'm going to push some tweaks on top of this

**Comment by cpanato** [comment]
> @cpanato -- I'm going to push some tweaks on top of this

Sounds great

**Review by justaugustus — APPROVED** [review]
@cpanato -- I've got more ideas and will issue in a new PR!

**Comment by justaugustus** [comment]
Continuing here: https://github.com/relengfam/peribolos/pull/22

**Pull request merged**
